#!/usr/bin/env bash

# commons
alias sudo="sudo "

# mutli-os colorized ls
alias ll="ls -lphG"
alias la="ls -laphG"
alias lsd="ls -lphG | grep '^d'"

OS_FLAVOR=$(uname -s)

if [[ "${OS_FLAVOR}" == "Darwin" ]]; then
  ignore_dirs="Appl|Desk|Down|Drop|Libr|Movi|Musi|Pict|Docu|Publ|Virt"
  alias ll="ls -lphG | grep -v -E '${ignore_dirs}'"
fi

# git/hub
if [[ -f "/usr/local/bin/hub" ]]; then
  eval "$(/usr/local/bin/hub alias -s)"
fi

# ruby ish
alias brake="bundle exec rake"
alias bint="bundle install --without system_tests --path=.bundle"
