#!/bin/bash

# keep colors after piping through grep
export CLICOLOR_FORCE='ls -G | less -R'

# make vim the default editor
export EDITOR=/usr/local/bin/vim;

# show three levels of pwd
export PROMPT_DIRTRIM=1

# history
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help:* -h";

# prefer us english and use utf-8
export LANG="en_US.UTF-8";

# highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# go setup
export GOROOT="/usr/local/go"
export GOPATH="${HOME}/golang"

# custom PATH
export PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/local/bin:${PATH}:/sbin"
