#!/bin/bash

# make vim the default editor
export EDITOR=/usr/local/bin/vim;

# show three levels of pwd
export PROMPT_DIRTRIM=3

# history
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help:* -h";

# prefer us english and use utf-8
export LANG="en_US.UTF-8";

# highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# don’t clear the screen after quitting a manual page
export MANPAGER="less -X";
