#!/usr/bin/env bash

# global path
export PATH="/usr/local/bin:${PATH}:/sbin"

# go path
export GOROOT="/usr/local/go"
export GOPATH="${HOME}/golang"
export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
