#
# zsh: exports
#
export GPG_TTY=$(tty)
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8"
export ZSH="${HOME}/.oh-my-zsh"
export EDITOR=/usr/local/bin/vim;
export PATH="/usr/local/go/bin:/usr/local/bin:${PATH}"

#
# zsh: theme
#
zstyle ':omz:alpha:lib:git' async-prompt no
ZSH_THEME="bullet-train"
BULLETTRAIN_PROMPT_ORDER=(
  time
  context
  dir
  git
)

#
# zsh: plugins
#
plugins=(
  argocd
  aws
  azure
  brew
  docker-compose
  docker
  dotenv
  gh
  git
  golang
  gradle
  helm
  history
  httpie
  kubectl
  kubectx
  pre-commit
  redis-cli
  rust
  sbt
  scala
  ssh-agent
  sudo
  ubuntu
)

#
# zsh: aliases
#
alias sudo="sudo "
alias ll="ls -lphG"
alias la="ls -laphG"
alias lsd="ls -lphG | grep '^d'"

#
# zsh: functions
#
mkd () {
  mkdir -p "$@"
}

tre () {
  tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
}

#
# zsh: kubernetes
#
alias kns='kubens'
alias ktx='kubectx'

k() {
	kubectl "$@"
}

#
# zsh: oh-my-zsh config (keep me last)
#
source $ZSH/oh-my-zsh.sh