# oh-my-zsh
export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="bullet-train"
zstyle ':omz:alpha:lib:git' async-prompt no

BULLETTRAIN_PROMPT_ORDER=(time dir git)
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_GIT_DIRTY=" 🔥"
BULLETTRAIN_GIT_CLEAN=" ✅"
BULLETTRAIN_GIT_ADDED=" ➕"
BULLETTRAIN_GIT_MODIFIED=" 🚧"
BULLETTRAIN_GIT_DELETED=" ❌"
BULLETTRAIN_GIT_UNTRACKED=" 🔍"
BULLETTRAIN_GIT_AHEAD=" 🚀"

plugins=(
    argocd
    aws
    azure
    bazel
    brew
    dotenv
    git
    gradle
    golang
    helm
    httpie
    kubectx
    pre-commit
    python
    rust
    sbt
    sudo
    themes
)
source $ZSH/oh-my-zsh.sh

# dude, where's my car?
export EDITOR=vim
export GPG_TTY=$(tty)
export LANG="en_US.UTF-8";
export GOROOT=/usr/local/go
export GOPATH="${HOME}/src/go"

export PATH_GOPATH="${GOPATH}/bin"
export PATH_GOROOT="${GOROOT}/bin"
export PATH_RANCHER="${HOME}/.rd/bin"
export PATH_VOLTA="${HOME}/.volta/bin"
export PATH_BREW_BIN="/opt/homebrew/bin"
export PATH_BREW_SBIN="/opt/homebrew/sbin"
export PATH="${PATH_GOPATH}:${PATH_GOROOT}:${PATH_RANCHER}:${PATH_VOLTA}:${PATH_BREW_BIN}:${PATH_BREW_SBIN}:${PATH}"

# shortcuts
alias vim="nvim"
alias sudo="sudo "
alias kns='kubens'
alias ktx='kubectx'
alias ll="ls -lphG"
alias la="ls -laphG"
eval "$(/opt/homebrew/bin/hub alias -s)"
alias lsd="ls -lphG | grep '^d'"

mkd () {
  mkdir -p "$@"
}

tre () {
  tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
}

k() {
	kubectl "$@"
}
