[[language]]
name = "markdown"
auto-format = true
formatter = {command = "prettier", args = ["--prose-wrap", "always", "--parser", "markdown"]}

[[language]]
name = "make"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-langserver"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.yaml"
